### ISSUE TITLE
 Url Param 'name' is missing

### ISSUE THREAD

**Issue by lonnietc** [jeroendk/go-vuejs-chat#5]
Hello,

I have been trying to run your v2 as I work through your tutorial but am getting an error:

2022/02/04 16:40:13 Url Param 'name' is missing

I am using:

go version go1.16 windows/amd64

**Comment by jeroendk** [comment]
Hi!

Where is this error showing up? When starting the Go service or in the frontend?

**Comment by antonpodkur** [comment]
Hello, basically frontend is broken, it says: 
normalize-slot.js:7 Uncaught TypeError: i.default.extend is not a function
    at normalize-slot.js:7:39
    at bootstrap-vue.min.js:10:225
    at bootstrap-vue.min.js:10:234
app.js:1 Uncaught TypeError: Vue is not a constructor
    at app.js:1:11

**Comment by juvenal-yescas** [comment]
In index.html replace 

`<script src="https://unpkg.com/vue"></script>`

with

`<script src="https://unpkg.com/vue@2.6.9/dist/vue.js"></script>`
